#
# A ConfigMap spec for phpldapadmin slapd that map directly to env variables in the Pod.
# List of environment variables supported is from the docker image:
# https://github.com/osixia/docker-phpLDAPadmin
# Note that passwords are defined as secrets
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "phpldapadmin.fullname" . }}-env-configmap
data:
{{ toYaml .Values.phpldapadmin.env | indent 2 }}