#
# A Secret spec for phpldapadmin containing passwords and other sensitive data
#
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "phpldapadmin.fullname" . }}-secret
  labels:
    app: {{ template "phpldapadmin.fullname" . }}
    version: {{ .Chart.Version }}  
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "-" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  PHPLDAPADMIN_LDAP_HOSTS:  {{ .Values.phpldapadmin.ldapHosts | b64enc | quote }}