# Default values for openldap.
# This is a YAML-formatted file.
#

openldap:
  replicas: 1
  image:
    # From repository https://github.com/osixia/docker-openldap
    name: osixia/openldap
    tag: 1.1.10

  ## Specify an imagePullPolicy (Required)
  ## It's recommended to change this to 'Always' if the image tag is 'latest'
  ## ref: http://kubernetes.io/docs/user-guide/images/#updating-images
  ##
  imagePullPolicy: IfNotPresent
  containerName: slapd

  serviceType: ClusterIP
  ldapInternalPort: 389
  ldapExternalPort: 389
  sslLdapInternalPort: 636
  sslLdapExternalPort: 636

  # Default configuration for openldap as environment variables. These get injected directly in the container.
  # Use the env variables from https://github.com/osixia/docker-openldap#beginner-guide
  env:
    LDAP_ORGANISATION: "Example Inc."
    LDAP_DOMAIN: "example.org"
    LDAP_BACKEND: "hdb"
    LDAP_TLS: "true"
    LDAP_TLS_ENFORCE: "false"
    LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"

  # Default Passwords to use. Unset these to auto-generate password stored as secrets.
  # You can override these at install time with
  # helm install openldap --set openldap.adminPassword=<passwd>,openldap.configPassword=<passwd>
  adminPassword: admin
  configPassword: config

  # Custom openldap configuration files used to override default settings
  customLdifFiles:
    # 01-default-users.ldif: |-
      # Predefine users here

  ## Persist data to a persitent volume
  persistence:
    enabled: false
    ## database data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 8Gi

  resources: {}
   # requests:
   #   cpu: "100m"
   #   memory: "256Mi"
   # limits:
   #   cpu: "500m"
   #   memory: "512Mi"

## test container details
openldaptest:
  image:
    name: dduportal/bats
    tag: 0.4.0
